[package]
name = "phabricator-oauth"
version = "0.1.3"
authors = ["Ilya Volchenkov <lzhepelmen@google.com>"]
edition = "2018"
description = "Library for OAuth2 authentication on Phabricator"
license = "MIT"
keywords = ["oauth", "oauth2", "phabricator", "authentication"]
repository = "https://github.com/lightwolf03/phabricator-oauth"

[lib]
name = "phabricator_oauth"
path = "src/lib.rs"

[dependencies]
oauth2 = "=4.0.0-alpha.3"
serde = "1.0"
serde_json = "1.0"
reqwest = { version = "0.11", default-features = false, features = ["blocking"] }